version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-backend
    ports:
      - "8000:8000"
    environment:
      APP_NAME: MyHotel
      APP_ENV: local
      APP_KEY: base64:gE9KsaHG2uCt15SXZdspudC+7q9ElaTwxP2v+rKHyt8=
      APP_DEBUG: 'true'
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hotel_app
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      BROADCAST_DRIVER: pusher
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      MEMCACHED_HOST: 127.0.0.1
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      PUSHER_APP_ID: 12345
      PUSHER_APP_KEY: ABCDE
      PUSHER_APP_SECRET: FGHIJK
      PUSHER_APP_CLUSTER: ap1
    depends_on:
      - db
      #- frontend
    volumes:
      - .:/var/www/html
    command: >
      sh -c "sleep 20 && php artisan migrate:fresh --seed && php artisan key:generate && php artisan serve --host 0.0.0.0 --port 8000"

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.vite
  #   container_name: vite-frontend
  #   restart: unless-stopped
  #   working_dir: /var/www/html
  #   volumes:
  #     - .:/var/www/html
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     NODE_ENV: development
  #     VITE_PUSHER_APP_KEY: ABCDE
  #     VITE_PUSHER_APP_CLUSTER: ap1
  #   command: [ "npm", "run", "dev" ]

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_app
    ports:
      - "3306:3306"
